#!/bin/zsh
#
# Quick shortcut to open VS Code. Run with no arguments to open the current directory.

# when on macOS, use `open` as it's faster than calling `code` directly
case "$OSTYPE" in
  darwin*)
    if [ "$1" = "" ] ; then
      open -a 'Visual Studio Code' .
    else
      open -a 'Visual Studio Code' "$@"
    fi
    ;;

  *)
    code_cmd="code"
    if [[ -n "$SSH_CLIENT" ]]; then
      code_cmd="code-ssh"
    fi
    if [ "$1" = "" ] ; then
      $code_cmd .
    else
      $code_cmd "$@"
    fi
    ;;
esac
