# Taps
tap 'cloudflare/cloudflare'
tap 'derailed/k9s'
tap 'derailed/popeye'
tap 'github/gh'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'replicatedhq/replicated'

# Formulae
brew 'ack'
brew 'ammonite-repl'
brew 'aws-iam-authenticator'
brew 'aws-okta'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'cabal-install'
brew 'ccache'
brew 'cloudflared'
brew 'coreutils'
brew 'deno'
brew 'docker-completion'
brew 'entr'
brew 'exa'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gh'
brew 'ghc'
brew 'git'
brew 'git-delta'
brew 'gnupg'
brew 'go'
brew 'gradle'
brew 'grc'
brew 'haskell-stack'
brew 'helmfile'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'ios-webkit-debug-proxy'
brew 'jq'
brew 'k9s'
brew 'kotlin'
brew 'krew'
brew 'ktlint'
brew 'kubernetes-cli'
brew 'kubectx'
brew 'kubeval'
brew 'kustomize'
brew 'mas'
brew 'mtr'
brew 'n'
brew 'node'
brew 'pgcli'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'poetry'
brew 'popeye'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'replicatedhq/replicated/cli'
brew 'rustup-init'
brew 'sbt'
brew 'scala'
brew 'sccache'
brew 'shellcheck'
brew 'starship'
brew 'stern'
brew 'telnet'
brew 'terraform-docs'
brew 'tfenv'
brew 'tflint'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zola'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# Casks
cask '1password'
cask '1password-cli'
cask 'authy'
cask 'ballast'
cask 'bettertouchtool'
cask 'blitz'
cask 'blu-ray-player-pro'
cask 'cleanmymac'
cask 'daisydisk'
cask 'dash'
cask 'dbngin'
cask 'deluge'
cask 'discord'
cask 'docker'
cask 'elgato-control-center'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive-file-stream'
cask 'hiddenbar'
cask 'hyper'
cask 'iconjar'
cask 'iina'
cask 'imageoptim'
cask 'insomnia'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'kaleidoscope'
cask 'kap'
cask 'keybase'
cask 'league-of-legends'
cask 'microsoft-edge'
cask 'minecraft'
cask 'now-tv-player'
cask 'oracle-jdk'
cask 'plex'
cask 'refined-github-safari'
cask 'signal'
cask 'sizeup'
cask 'skype'
cask 'slack'
cask 'sonos'
cask 'sony-ps4-remote-play'
cask 'spotify'
cask 'sublime-text'
cask 'tableplus'
cask 'the-unarchiver'
cask 'transmission'
cask 'twitch'
cask 'transmit'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'wire'
cask 'zoomus'

# Fonts
cask 'font-hasklig'
cask 'font-source-code-pro'

# Mac App Store Applications
mas '1Blocker', id: 1_107_421_413
mas 'Apple Configurator 2', id: 1_037_126_344
mas 'Dato', id: 1_470_584_107
mas 'Fantastical', id: 975_937_182
mas 'Jiffy', id: 1_502_527_999
mas 'Lungo', id: 1_263_070_803
mas 'Microsoft Excel', id: 462_058_435
mas 'Microsoft Remote Desktop 10', id: 1_295_203_466
mas 'Microsoft Word', id: 462_054_704
mas 'Pixelmator', id: 407_963_104
mas 'Reeder 4', id: 1_449_412_482
mas 'Things 3', id: 904_280_696
mas 'Tweetbot', id: 1_384_080_005
mas 'WireGuard', id: 1_451_685_025
mas 'Xcode', id: 497_799_835
