# Taps
tap 'aws/tap'
tap 'cloudflare/cloudflare'
tap 'derailed/k9s'
tap 'derailed/popeye'
tap 'dtan4/tools'
tap 'fluxcd/tap'
tap 'github/gh'
tap 'hashicorp/tap'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'imhotepio/k9salpha'
tap 'jacobwgillespie/tap'
tap 'orf/brew'
tap 'superfly/tap'
tap 'xwmx/taps'

# Formulae
brew 'ack'
brew 'aws-iam-authenticator'
brew 'awscli'
brew 'azure-cli'
brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'berglas'
brew 'buildifier'
brew 'caddy'
brew 'calicoctl'
brew 'ccache'
brew 'chamber'
brew 'cloudflared'
brew 'cmake'
brew 'coreutils'
brew 'deno'
brew 'dive'
brew 'doctl'
brew 'dog'
brew 'entr'
brew 'exa'
brew 'fd'
brew 'ffmpeg'
brew 'flux'
brew 'flyctl'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'gnupg'
brew 'go'
brew 'gping'
brew 'gradle'
brew 'grc'
brew 'grep'
brew 'hadolint'
brew 'helmfile'
brew 'httpie'
brew 'hosts'
brew 'hub'
brew 'icdiff'
brew 'imagemagick'
brew 'ios-webkit-debug-proxy'
brew 'jq'
brew 'k8sec'
brew 'k9s'
brew 'k9salpha'
brew 'kind'
brew 'kotlin'
brew 'krew'
brew 'ktlint'
brew 'kubernetes-cli'
brew 'kubectx'
brew 'kustomize'
brew 'librsvg'
brew 'mas'
brew 'massren'
brew 'minikube'
brew 'mtr'
brew 'n'
brew 'node'
brew 'openssh'
brew 'pgcli'
brew 'pgformatter'
brew 'postgresql'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'poetry'
brew 'popeye'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rancher-cli'
brew 'rustup-init'
brew 'sccache'
brew 'shellcheck'
brew 'sops'
brew 'starship'
brew 'stern'
brew 'subversion'
brew 'swi-prolog'
brew 'telnet'
brew 'terraform-docs'
brew 'tflint'
brew 'tf-shim'
brew 'watchman'
brew 'waypoint'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zola'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# Casks
cask '1password'
cask 'ableton-live-intro'
cask 'adobe-creative-cloud'
cask 'authy'
cask 'balance-lock'
cask 'bettertouchtool'
cask 'blackhole-16ch'
cask 'blackhole-2ch'
cask 'blitz'
cask 'blu-ray-player-pro'
cask 'blue-sherpa'
cask 'cleanmymac'
cask 'daisydisk'
cask 'dash'
cask 'datagrip'
cask 'dbngin'
cask 'discord'
cask 'docker'
cask 'dynobase'
cask 'elgato-control-center'
cask 'expressions'
cask 'figma'
cask 'firefox'
cask 'github'
cask 'google-cloud-sdk'
cask 'hey'
cask 'hiddenbar'
cask 'hyper'
cask 'iconjar'
cask 'iina'
cask 'imageoptim'
cask 'insomnia'
cask 'iterm2'
cask 'kaleidoscope'
cask 'kap'
cask 'keybase'
cask 'kube-forwarder'
cask 'league-of-legends'
cask 'linear-linear'
cask 'microsoft-auto-update'
cask 'microsoft-edge'
cask 'microsoft-outlook'
cask 'minecraft'
cask 'monitorcontrol'
cask 'oracle-jdk'
cask 'paw'
cask 'pgadmin4'
cask 'pingplotter'
cask 'plex'
cask 'proxyman'
cask 'raycast'
cask 'session-manager-plugin'
cask 'signal'
cask 'slack'
cask 'sonos'
cask 'sony-ps4-remote-play'
cask 'spotify'
cask 'steam'
cask 'sublime-text'
cask 'tableplus'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'twitch'
cask 'typora'
cask 'unite'
cask 'visual-studio-code'
cask 'vlc'
cask 'webstorm'
cask 'whatsapp'
cask 'wire'
cask 'zoom'

# Fonts
cask 'font-hasklig'
cask 'font-inter'
cask 'font-jetbrains-mono'
cask 'font-source-code-pro'

# Mac App Store Applications
mas '1Blocker', id: 1_365_531_024
mas 'Apple Configurator 2', id: 1_037_126_344
mas 'Dato', id: 1_470_584_107
mas 'Jiffy', id: 1_502_527_999
mas 'Lungo', id: 1_263_070_803
mas 'Microsoft Excel', id: 462_058_435
mas 'Microsoft Remote Desktop 10', id: 1_295_203_466
mas 'Microsoft Word', id: 462_054_704
mas 'Pixelmator Pro', id: 1_289_583_905
mas 'Poolside FM', id: 1_514_817_810
mas 'Reeder 5', id: 1_529_448_980
mas 'Refined GitHub', id: 1_519_867_270
mas 'Simplify for Gmail', id: 1_544_668_450
mas 'Tweetbot', id: 1_384_080_005
mas 'WireGuard', id: 1_451_685_025
mas 'Xcode', id: 497_799_835
